
##__________________________________________________________________||
lambdaStrDict = {
    'JSON': "ev : ev.inCertifiedLumiSections[0]",
    'ht40_loose_JECvar': 'ev : ev.ht40JECUp[0] >= 150',
    'nJet100_JECvar': 'ev : ev.nJet100JECUp[0] >= 1',
    'ht_JECvar': "ev : ev.ht40JECUp[0] >= 200",
    'mht': "ev : 130 <= ev.mht40_pt[0]",
    'mht_JECvar': "ev : 130 <= max(ev.mht40_pt[0], ev.mht40JECUp_pt[0], ev.mht40JECDown_pt[0])",
    'alphaT': "ev : {v} <= ev.alphaT[0]",
    'alphaT_JECvar': "ev : {v} <= max(ev.alphaT[0], ev.alphaTJECUp[0], ev.alphaTJECDown[0])",
    'biasedDPhi': "ev : 0.5 <= ev.biasedDPhi[0]",
    'biasedDPhi20': "ev : ev.biasedDPhi20[0] == -1 or 0.5 <= ev.biasedDPhi20[0]",
    'mtw': "ev : 30 <= ev.mtw[0] < 125",
    'mtwNoHF': "ev : 30 <= ev.mtwNoHF[0] < 125",
    'mll': "ev : 66.2 <= ev.mll[0] < 116.2",
    'isoTrackVeto': "ev : ev.nIsoTracksVeto[0] <= 0",
    'isoTrackNoMuVeto': "ev : ev.nIsoTracksNoMuVeto[0] <= 0",
    'isoTrackNoEleVeto': "ev : ev.nIsoTracksNoEleVeto[0] <= 0",
    'nMuonsIsolated': 'ev : ev.nMuonsIsolated[0] == {n}',
    'nElectronsIsolated': 'ev : ev.nElectronsIsolated[0] == {n}',
    'nElectronsBarrel': 'ev : ev.nElectronsBarrel[0] == {n}',
    'nPhotons200': 'ev : ev.nPhotons200[0] == {n}',
    'minDelRJetMu': "ev : ev.minDelRJetMu[0] >= 0.5",
    'minDelRJetEle': "ev : ev.minDelRJetEle[0] >= 0.5",
    'minDelRJetPhoton': "ev : ev.minDelRJetPhoton[0] >= 1.0",
    'bintype_monojet': "ev : ev.bintypeId[0] == 1 # 'monojet'",
    'bintype_asymjet': "ev : ev.bintypeId[0] == 2 # 'asymjet'",
    'bintype_symjet': "ev : ev.bintypeId[0] == 3 # 'symjet'",
    'bintype_highht': "ev : ev.bintypeId[0] == 4 # 'highht'",
    'bintype_monojet_JECvar': "ev : 1 in (ev.bintypeId[0], ev.bintypeIdJECUp[0], ev.bintypeIdJECDown[0]) # 'monojet'",
    'bintype_asymjet_JECvar': "ev : 2 in (ev.bintypeId[0], ev.bintypeIdJECUp[0], ev.bintypeIdJECDown[0]) # 'asymjet'",
    'bintype_symjet_JECvar': "ev : 3 in (ev.bintypeId[0], ev.bintypeIdJECUp[0], ev.bintypeIdJECDown[0]) # 'symjet'",
    'bintype_highht_JECvar': "ev : 4 in (ev.bintypeId[0], ev.bintypeIdJECUp[0], ev.bintypeIdJECDown[0]) # 'highht'",
    'cutflow_Signal': "ev : ev.cutflowId[0] == 1 # 'Signal'",
    'cutflow_SingleMu': "ev : ev.cutflowId[0] == 2 # 'SingleMu'",
    'cutflow_DoubleMu': "ev : ev.cutflowId[0] == 3 # 'DoubleMu'",
    'cutflow_SingleEle': "ev : ev.cutflowId[0] == 4 # 'SingleEle'",
    'cutflow_DoubleEle': "ev : ev.cutflowId[0] == 5 # 'DoubleEle'",
    'cutflow_SinglePhoton': "ev : ev.cutflowId[0] == 6 # 'SinglePhoton'",
    'htbin_200': "ev : ev.htbin[0] == 200",
    'htbin_250': "ev : ev.htbin[0] == 250",
    'htbin_300': "ev : ev.htbin[0] == 300",
    'htbin_350': "ev : ev.htbin[0] == 350",
    'htbin_400': "ev : ev.htbin[0] == 400",
    'htbin_600': "ev : ev.htbin[0] == 600",
    'htbin_800': "ev : ev.htbin[0] == 800",
    'htbin_200_JECvar': "ev : 200 <= ev.ht40JECUp[0] and ev.ht40JECDown[0] < 250",
    'htbin_250_JECvar': "ev : 250 <= ev.ht40JECUp[0] and ev.ht40JECDown[0] < 300",
    'htbin_300_JECvar': "ev : 300 <= ev.ht40JECUp[0] and ev.ht40JECDown[0] < 350",
    'htbin_350_JECvar': "ev : 350 <= ev.ht40JECUp[0] and ev.ht40JECDown[0] < 400",
    'htbin_400_JECvar': "ev : 400 <= ev.ht40JECUp[0] and ev.ht40JECDown[0] < 600",
    'htbin_600_JECvar': "ev : 600 <= ev.ht40JECUp[0] and ev.ht40JECDown[0] < 800",
    'htbin_800_JECvar': "ev : 800 <= ev.ht40JECUp[0]",
    'PD_MET': "ev : ev.PrimaryDataset[0] == 'MET'",
    'PD_HTMHT': "ev : ev.PrimaryDataset[0] == 'HTMHT'",
    'PD_JetHT': "ev : ev.PrimaryDataset[0] == 'JetHT'",
    'PD_SingleElectron': "ev : ev.PrimaryDataset[0] == 'SingleElectron'",
    'PD_SingleMuon': "ev : ev.PrimaryDataset[0] == 'SingleMuon'",
    'PD_SinglePhoton': "ev : ev.PrimaryDataset[0] == 'SinglePhoton'",
}

##__________________________________________________________________||
